---
pagetitle: "What to do next"
---

# What to do next {#what-to-do-next}

These are further projects that appear feasible and worthwhile, but they work less well as immediate follow-up projects: for example because (1) scope is large, (2) scope needs to be defined better, (3) there are some "path critical" steps on the way, or (4) we are less certain how directly they would relate to more optimal choices.

- **Primary research, correlates of protection.** This one is most wide-ranging and perhaps obvious: if we want to avoid making dosing decisions based on clinical trials of 10,000's of subjects that compare different doses, we need strong understanding of how immune response is achieved. To name one specific target here (from my interviews), while we have correlates of protection for influenza, we also know that with adjuvants the mechanism of protection changes. So a simple model of dose-response will predict low efficacy for low dose of flu vaccine coupled with adjuvants, but some experimental data suggests this is not the case. Supporting research into this type of problems would be crucial for optimisation in pandemic influenza.

- **Emphasise dosing/schedules and public health perspective in regulatory guidelines; encourage/demand optimisation for publicly funded vaccines.** As I discussed, the guidelines have little to say about justification of optimal dosing and even less about public health benefits. It is not the job of regulators to worry about supply, but if multiple doses perform similarly, they could encourage manufacturers to seek approval for a range of doses. There are obvious reasons why we should not simply push too hard to approve lower doses, e.g. immune escape; usually it's better to overshoot with doses, if there is enough sparing. But this is not an argument against generating relevant data for dose sparing, which regulators could request from vaccine makers. This should especially be done in the cases where vaccines are publicly funded.

- **Push for clinical trial data to be made available, quickly.** A lot of data that are useful for developing new vaccines are siloed. For example, if I am developing a new CVOID mRNA vaccine and want to understand how waning of protection depends on dosing, I can probably develop good priors (= make better decisions for my trial) based on individual-level immunogenicity time-course data from Pfizer and Moderna trials. Currently the best case scenario is that I can find some of the relevant data and then digitise some plots by hand. Same point about doing this more aggressively for tax-sponsored vaccines applies here.

- **Comprehensively and continuously identify gaps in evidence on optimal use.** This report attempts to point out some gaps, but it is nowhere close to a comprehensive review for all vaccines that are in routine use or clinical development. A group focused specifically on this type of evaluation (and continually bringing them into hands of relevant groups: WHO, Gavi, NITAGs, ...) may be valuable. This may be simply fostering collaboration between health technology assessment groups rather than setting up any new capacity, but in any case it needs to be explored.

- **Establishing clear evidence requirements and framework for dose sparing decisions, especially in pandemics.** There has been a lot of discussion about how to "beef up" vaccine prioritisation decisions both globally and in particular countries. I have not been able to investigate this in detail, but it seems that what would be needed here is to bring more of optimisation perspective into systems that exist or are being set up. In plain text, this is about having a blueprint for relevant decision makers that they could use to make better choices on dosing/schedules in the next pandemic.

- **Establish feasibility of intradermal delivery**. ID has been proven as a viable alternative for many vaccines and may be necessary for future pandemics. However, decision makers seem wary of it: I discussed in detail the assessment of ID delivery of influenza vaccines. Finding opportunities to roll it out at scale, while simultaneously working with decision makers may help overcome this. There have been various large proof-of-concept studies for ID delivery of IPV, but I wonder if this needs to be done for other vaccines or in more specific settings.

- **Fostering commercialisation of new administration methods.** This one is a bit outside of my area of expertise, but the benefits to optimal dosing are clear: if the ID delivery devices were cost-effective and more convenient than IM delivery, then it would be easier to decrease/adjust dosing.
