---
pagetitle: "Research agenda"
---

# Research agenda {#research-agenda}

{{< include ../includes/note-disclaimer.qmd >}}

## Conclusions and next steps {#conclusions-and-next-steps}

Two main points emerge from the notes I compiled:

1.  Optimal use of vaccines could have large impacts in particular situations, often working as a complement to market design. Because the biological mechanisms involved are pretty general, there are many candidate vaccines. Both vaccine development and decision making on immunisations are likely not optimal.

2.  Optimisation is technologically feasible, but under the status quo can be prohibitively expensive and politically undesirable.

What are the solutions? An obvious, but also pie-in-the-sky, solution would be systemic, aimed at redesigning the paradigm of evidence generation and decision making. In broad strokes, that means (1) conducting faster and cheaper trials on relevant questions and (2) public health decision making that is responsive to new evidence and comfortable with risk-benefit analysis under uncertainty. Effecting even small change to either of these is of course an incredibly complex problem. At the same time, this may be the most worthwhile task.

Instead, I focus on an at-the-margins approach of making many isolated contributions to this problem by a funder spending money wisely to sponsor individual initiatives or pieces of research. What kind of difference could such a funder make?

I suggest a few projects that apply across many vaccines/diseases (see previous section for disease-specific recommendations). I divide this list into

- six projects that could be implemented soon,

- six extra areas to investigate (which could translate to some projects),

- six pathways to future change (things that seem feasible to do, but they need more info).

## Four potential projects that could be done right now {#four-potential-projects-that-could-be-done-right-now}

### 1: Connecting different groups/stakeholders  {#connecting-different-groupsstakeholders}

I got an impression that there are several groups where there is potentially need for more exchange of information. I'd recommend first interviewing

**Stage 1, fact finding** (deeper investigation/narrower scope than this document), partitioned into particular groups, with a defined set of questions for each:

- Vaccine researchers: current/best practices for first-in-human dose choices, dose de-escalation, and tools that they use for escalating doses and picking dosing schedules in Phase 1-2

- Regulators (FDA, EMA, MHRA): their attitude to vaccine dosing and schedules in clinical development, e.g. requirements and guidelines for dose finding, dose and schedule justification. In particular, understand if there are plans to develop guidelines for dosing/schedules during clinical development.

- Modellers (experts on model-based vaccine/drug development methods): the current state of these tools, prospects for wider adoption.[^agenda-projects-1]

- Decision makers (WHO, Gavi, at least several national level case studies): what exactly is needed to change vaccine dosing or schedules in specific contexts (i.e. specific diseases, in specific countries, across several case studies)

**Stage 2, workshops/working groups**; depending on the outcomes of stage 1. Each of this can be a separate project in its own right, this list is grouped for convenience (and because I expect only a couple of them to be genuinely worth doing):

- Conduct a workshop for researchers if it feels like there needs to be some exchange of information on dose/regiment selection (e.g. dose escalation or first-in-human dosing, de-escalation best practices)

- Conduct a workshop putting together researchers and regulators, e.g. to scope potential guidelines for dose selection and dose justification. Possible also work on a brief addressed at regulators for proposed changes to regulatory approach.

- Conduct a workshop connecting clinical researchers and modellers, to discuss value and adoption of models in clinical development.

- Create a working group connecting decision makers and regulators to create concrete proposals aimed at making better and faster vaccine optimisation decisions. (At the time of writing I am already in conversation about this with colleagues at Center for Global Development.)

Broadly speaking, intended outcomes of these would be better vaccine dosing/schedule decisions during development, more dose de-escalation data being generated, more incentive to consider lower doses in seeking approval, and faster decisions around recommending alternative vaccine regimens.

### 2: Write a "big name" paper to raise awareness of benefits of dose sparing or fractionation {#write-a-big-name-paper-to-raise-awareness-of-benefits-of-dose-sparing-or-fractionation}

An obvious recommendation in such situations, but in this case there is an extra justification that these topics may genuinely be somewhat unfamiliar to relevant decision makers.[^agenda-projects-2] Note that the message would be specifically about lower doses or increasing gaps between doses, i.e. stretching supply.

The idea would be to write a research article or commentary that summarises basic information covered in this report and potentially makes several general recommendations. This could be then used to start or progress some conversations with decision makers.

What we know:

- Optimisation has many benefits. It plays especially crucial role in pandemics

- Fractionation and delayed doses has been shown to be beneficial and successfully implemented for several diseases; it's been shown to be feasible even in difficult settings

- It has not been systematically tested and there are reasons to believe it could benefit more existing vaccines

Example recommendations of such an article could be

1.  Sponsor more optimisation research for existing vaccines (e.g. de-escalation)

2.  More emphasis on socially optimal choices during clinical development (as opposed to leaving it until/after the approval)

3.  Develop frameworks for dose sparing decisions during shortages

This project can also include some awareness building, e.g. by op-ed writing etc, but I think this is less valuable than one or two articles by widely respected researchers.

### 3: Further investigating dose de-escalation: literature review and sponsoring studies {#further-investigating-dose-de-escalation-literature-review-and-sponsoring-studies}

This project is potentially most directly valuable of the four listed here, but the description is short, because I have least information to plan this ahead of time. This project would probably have two sub-component.

**Conduct literature review**

As one expert put it, "if you had a paper with some exemplars on how you can drop dose 10x would, this would motivate people." A starting point would be to conduct a literature review on choice of doses at each stage of development, to get a sense if they initially under- or overdose. I have not been able to investigate this deeply, but it seems that there isn't much literature on this.

**Sponsor some small studies**

Following the literature review, there may be some obvious promising vaccine candidates for which we would like to systematically conduct de-escalation studies. Some isolated examples already exist and are cited in this report, but this is usually done ad hoc and it would take more expertise.

### 4: Support proof-of-concepts for trials {#support-proof-of-concepts-for-trials}

I propose trying out two proofs of concept for clinical trials that can help inform the choice of optimal vaccine schedules.

**Phase 3 RCTs with multiple doses**

If late into clinical development several doses or schedules look like good candidates in large-scale trials, it may be worth randomising people into several arms/schedules.[^agenda-projects-3] COVID-19 is a good example; if 50, and 100 mcg doses of Moderna's mRNA-1273 had similar immunological profile following Phase 2 and both seemed likely to work, why for Phase 3 not randomise patients 1:1:2 to 100 mcg, 50 mcg, and placebo respectively? Data in vaccinated patients could then either be merged to calculate a single efficacy metric (as it was de facto done in the AstraZeneca vaccine trial) or synthesised through dose-response modeling (using immunological data). Such a trial may still be underpowered for proving non-inferiority of the lower dosage, but it provides many times more data than the original trial.

Clinical trials of efficacy against infection, not just against disease

Let us imagine a hypothetical epidemic, where cases are growing exponentially and the spread is not controlled, but a new vaccine potentially offers some protection against infection. The optimal dosing in the case of transmission-breaking vaccine is going to be different.[^agenda-projects-4] Thus generating data on sterilising immunity may be very important for vaccine optimisation. This may look like "traditional" field trials with regular testing of a large population and studying secondary infections.

**What to do**

In both of these cases the objective would be two-fold

(1) consider trial design under realistic conditions (e.g. based on retrospective analysis of COVID)

(2) describe both risk-benefits of statistical trial designs that are not commonly used, in the sense of utility of generated information for both general licensure and making more optimal vaccine schedule choices (e.g. a trial with multiple doses may get closer to socially optimal dose but reduce overall approval probability), but also accounting for patient risks and costs

(3) (optionally) in both cases consider how these data could be generated by using human challenge trials

[^agenda-projects-1]: Why investigate this more? Even if researchers switch their mindset to more comprehensively testing more doses and schedules early in vaccine development, there is no guarantee that this will yield optimal results. On the other hand, it's unclear whether some of the modelling approaches are practically valuable or just mainly proofs-of-concept that are not ready to be used in most practical cases.

[^agenda-projects-2]: A good example for work in that category is a recent article showing safety and growing adoption of human challenge studies.

[^agenda-projects-3]: Why is this not done? Developers don't see this as an option, because trials are so expensive and they would like to avoid anything that would increase trial sizes, even modestly. Most researchers and regulators may be averse to considering this because they are generally resistant to synthesising information in clinical trials: we demonstrated this unwillingness to generalise in several examples throughout the document.

[^agenda-projects-4]: If we knew the vaccine offered protection from infection, then it may be optimal to quickly give it to as many people as possible (at the dose at which there is enough efficacy against infection), to break transmission/reach herd immunity. If that is not the case, then we may focus on vaccinating the at-risk individuals (at the dose at which there is efficacy against disease).

## What I still don't understand {#what-i-still-dont-understand}

There are several areas that feel like they could yield some tangible projects, but which I was not able to investigate for this report because I ran out of time or were not able to schedule relevant meetings.

- How market design and AMCs could impact not just supply, but also optimisation. Related to this, get more of a perspective of health economists: ones working in LMICs on acceptability and value of lower doses and ones specialising in pricing, to understand how unilateral decisions to fractionate would impact prices.

- Interview experts on optimisation in particular vaccines, especially on connections with policy. (More context in summary of optimisation targets.) I have three particular recommendations: Andrew Clark on optimisation of rotavirus vaccines, Ian Spicknall (and someone extra at FDA) to better understand the case of mpox modeling and approval (which may have implications for future epidemics in wealthy countries), Andrew Azman or Justin Lesler on cholera vaccine.

- Model-based vaccine development experts, together with some vaccine developers, to understand current decision making process and how better tools could benefit the process. Examples of interviewees here would be LSTHM modellers and Tom Evans, ex-CEO of Vaccitech.

- Find policy experts knowledgeable about national strategies against pandemic influenza and other pandemic threats, assess existing plans.

- Investigate more practical questions on ID dosing. For example, what are the barriers to widespread ID vaccination in terms of availability of LDS? Can we make LDSS more widely available? Is it feasible to accelerate availability of jet injectors?

## What to do next {#what-to-do-next}

These are further projects that appear feasible and worthwhile, but they work less well as immediate follow-up projects: for example because (1) scope is large, (2) scope needs to be defined better, (3) there are some "path critical" steps on the way, or (4) we are less certain how directly they would relate to more optimal choices.

- **Primary research, correlates of protection.** This one is most wide-ranging and perhaps obvious: if we want to avoid making dosing decisions based on clinical trials of 10,000's of subjects that compare different doses, we need strong understanding of how immune response is achieved. To name one specific target here (from my interviews), while we have correlates of protection for influenza, we also know that with adjuvants the mechanism of protection changes. So a simple model of dose-response will predict low efficacy for low dose of flu vaccine coupled with adjuvants, but some experimental data suggests this is not the case. Supporting research into this type of problems would be crucial for optimisation in pandemic influenza.

- **Emphasise dosing/schedules and public health perspective in regulatory guidelines; encourage/demand optimisation for publicly funded vaccines.** As I discussed, the guidelines have little to say about justification of optimal dosing and even less about public health benefits. It is not the job of regulators to worry about supply, but if multiple doses perform similarly, they could encourage manufacturers to seek approval for a range of doses. There are obvious reasons why we should not simply push too hard to approve lower doses, e.g. immune escape; usually it's better to overshoot with doses, if there is enough sparing. But this is not an argument against generating relevant data for dose sparing, which regulators could request from vaccine makers. This should especially be done in the cases where vaccines are publicly funded.

- **Push for clinical trial data to be made available, quickly.** A lot of data that are useful for developing new vaccines are siloed. For example, if I am developing a new CVOID mRNA vaccine and want to understand how waning of protection depends on dosing, I can probably develop good priors (= make better decisions for my trial) based on individual-level immunogenicity time-course data from Pfizer and Moderna trials. Currently the best case scenario is that I can find some of the relevant data and then digitise some plots by hand. Same point about doing this more aggressively for tax-sponsored vaccines applies here.

- **Comprehensively and continuously identify gaps in evidence on optimal use.** This report attempts to point out some gaps, but it is nowhere close to a comprehensive review for all vaccines that are in routine use or clinical development. A group focused specifically on this type of evaluation (and continually bringing them into hands of relevant groups: WHO, Gavi, NITAGs, ...) may be valuable. This may be simply fostering collaboration between health technology assessment groups rather than setting up any new capacity, but in any case it needs to be explored.

- **Establishing clear evidence requirements and framework for dose sparing decisions, especially in pandemics.** There has been a lot of discussion about how to "beef up" vaccine prioritisation decisions both globally and in particular countries. I have not been able to investigate this in detail, but it seems that what would be needed here is to bring more of optimisation perspective into systems that exist or are being set up. In plain text, this is about having a blueprint for relevant decision makers that they could use to make better choices on dosing/schedules in the next pandemic.

- **Establish feasibility of intradermal delivery**. ID has been proven as a viable alternative for many vaccines and may be necessary for future pandemics. However, decision makers seem wary of it: I discussed in detail the assessment of ID delivery of influenza vaccines. Finding opportunities to roll it out at scale, while simultaneously working with decision makers may help overcome this. There have been various large proof-of-concept studies for ID delivery of IPV, but I wonder if this needs to be done for other vaccines or in more specific settings.

- **Fostering commercialisation of new administration methods.** This one is a bit outside of my area of expertise, but the benefits to optimal dosing are clear: if the ID delivery devices were cost-effective and more convenient than IM delivery, then it would be easier to decrease/adjust dosing.

## Five reasons to be negative about these proposals {#five-reasons-to-be-negative-about-these-proposals}

There are many criticisms at many levels that can be mentioned here, but I wanted to reiterate five points that I may have not made sufficiently in my notes:

- New technologies may blunt the value of fractionation in the longer term. New vaccine platforms will deliver better vaccines, cheaply and with supply difficulties. Increasingly, the move toward combination vaccines and pre-filled syringes may close the window for the type of fractionation I focussed on here.

- Optimisation is always just a complement to maximising supply and coverage. And its uncertain (to me) what effect changes to dosing would have on costs and supply.

- There is no immediate exciting research that I was able to identify. E.g. none of my interviewees or sources that I read had a specific suggestion for an optimisation study that needed to be funded urgently. All the projects discussed are a form of gradualism.

- It will always be hard to meet the threshold of certainty that decision makers require. For example, even with a much more comprehensive research agenda on optimisation of COVID vaccines in 2020-2021, I still suspect that data on lower doses would not be deemed sufficient.

- Any optimisation is difficult and doesn't work in isolation. If trying to speed up vaccinations, the law of the minimum kicks in: sometimes there are other logistical, administrative, programmatic constraints. You have to plan for all of these things in order to make a difference.

I think that's all! Thanks for reading, this has been really nice to work on.

The rest of this document is an appendix containing my four case studies.

Appendix: four case studies
