---
pagetitle: "What I still don’t understand"
---

# What I still don't understand {#what-i-still-dont-understand}

There are several areas that feel like they could yield some tangible projects, but which I was not able to investigate for this report because I ran out of time or were not able to schedule relevant meetings.

- How market design and AMCs could impact not just supply, but also optimisation. Related to this, get more of a perspective of health economists: ones working in LMICs on acceptability and value of lower doses and ones specialising in pricing, to understand how unilateral decisions to fractionate would impact prices.

- Interview experts on optimisation in particular vaccines, especially on connections with policy. (More context in summary of optimisation targets.) I have three particular recommendations: Andrew Clark on optimisation of rotavirus vaccines, Ian Spicknall (and someone extra at FDA) to better understand the case of mpox modeling and approval (which may have implications for future epidemics in wealthy countries), Andrew Azman or Justin Lesler on cholera vaccine.

- Model-based vaccine development experts, together with some vaccine developers, to understand current decision making process and how better tools could benefit the process. Examples of interviewees here would be LSTHM modellers and Tom Evans, ex-CEO of Vaccitech.

- Find policy experts knowledgeable about national strategies against pandemic influenza and other pandemic threats, assess existing plans.

- Investigate more practical questions on ID dosing. For example, what are the barriers to widespread ID vaccination in terms of availability of LDS? Can we make LDSS more widely available? Is it feasible to accelerate availability of jet injectors?
