---
pagetitle: "Four potential projects that could be done right now"
---

# Four potential projects that could be done right now {#four-potential-projects-that-could-be-done-right-now}

## 1: Connecting different groups/stakeholders  {#connecting-different-groupsstakeholders}

I got an impression that there are several groups where there is potentially need for more exchange of information. I'd recommend first interviewing

**Stage 1, fact finding** (deeper investigation/narrower scope than this document), partitioned into particular groups, with a defined set of questions for each:

- Vaccine researchers: current/best practices for first-in-human dose choices, dose de-escalation, and tools that they use for escalating doses and picking dosing schedules in Phase 1-2

- Regulators (FDA, EMA, MHRA): their attitude to vaccine dosing and schedules in clinical development, e.g. requirements and guidelines for dose finding, dose and schedule justification. In particular, understand if there are plans to develop guidelines for dosing/schedules during clinical development.

- Modellers (experts on model-based vaccine/drug development methods): the current state of these tools, prospects for wider adoption.[^1]

- Decision makers (WHO, Gavi, at least several national level case studies): what exactly is needed to change vaccine dosing or schedules in specific contexts (i.e. specific diseases, in specific countries, across several case studies)

**Stage 2, workshops/working groups**; depending on the outcomes of stage 1. Each of this can be a separate project in its own right, this list is grouped for convenience (and because I expect only a couple of them to be genuinely worth doing):

- Conduct a workshop for researchers if it feels like there needs to be some exchange of information on dose/regiment selection (e.g. dose escalation or first-in-human dosing, de-escalation best practices)

- Conduct a workshop putting together researchers and regulators, e.g. to scope potential guidelines for dose selection and dose justification. Possible also work on a brief addressed at regulators for proposed changes to regulatory approach.

- Conduct a workshop connecting clinical researchers and modellers, to discuss value and adoption of models in clinical development.

- Create a working group connecting decision makers and regulators to create concrete proposals aimed at making better and faster vaccine optimisation decisions. (At the time of writing I am already in conversation about this with colleagues at Center for Global Development.)

Broadly speaking, intended outcomes of these would be better vaccine dosing/schedule decisions during development, more dose de-escalation data being generated, more incentive to consider lower doses in seeking approval, and faster decisions around recommending alternative vaccine regimens.

## 2: Write a "big name" paper to raise awareness of benefits of dose sparing or fractionation {#write-a-big-name-paper-to-raise-awareness-of-benefits-of-dose-sparing-or-fractionation}

An obvious recommendation in such situations, but in this case there is an extra justification that these topics may genuinely be somewhat unfamiliar to relevant decision makers.[^2] Note that the message would be specifically about lower doses or increasing gaps between doses, i.e. stretching supply.

The idea would be to write a research article or commentary that summarises basic information covered in this report and potentially makes several general recommendations. This could be then used to start or progress some conversations with decision makers.

What we know:

- Optimisation has many benefits. It plays especially crucial role in pandemics

- Fractionation and delayed doses has been shown to be beneficial and successfully implemented for several diseases; it's been shown to be feasible even in difficult settings

- It has not been systematically tested and there are reasons to believe it could benefit more existing vaccines

Example recommendations of such an article could be

1.  Sponsor more optimisation research for existing vaccines (e.g. de-escalation)

2.  More emphasis on socially optimal choices during clinical development (as opposed to leaving it until/after the approval)

3.  Develop frameworks for dose sparing decisions during shortages

This project can also include some awareness building, e.g. by op-ed writing etc, but I think this is less valuable than one or two articles by widely respected researchers.

## 3: Further investigating dose de-escalation: literature review and sponsoring studies {#further-investigating-dose-de-escalation-literature-review-and-sponsoring-studies}

This project is potentially most directly valuable of the four listed here, but the description is short, because I have least information to plan this ahead of time. This project would probably have two sub-component.

**Conduct literature review**

As one expert put it, "if you had a paper with some exemplars on how you can drop dose 10x would, this would motivate people." A starting point would be to conduct a literature review on choice of doses at each stage of development, to get a sense if they initially under- or overdose. I have not been able to investigate this deeply, but it seems that there isn't much literature on this.

**Sponsor some small studies**

Following the literature review, there may be some obvious promising vaccine candidates for which we would like to systematically conduct de-escalation studies. Some isolated examples already exist and are cited in this report, but this is usually done ad hoc and it would take more expertise.

## 4: Support proof-of-concepts for trials {#support-proof-of-concepts-for-trials}

I propose trying out two proofs of concept for clinical trials that can help inform the choice of optimal vaccine schedules.

**Phase 3 RCTs with multiple doses**

If late into clinical development several doses or schedules look like good candidates in large-scale trials, it may be worth randomising people into several arms/schedules.[^3] COVID-19 is a good example; if 50, and 100 mcg doses of Moderna's mRNA-1273 had similar immunological profile following Phase 2 and both seemed likely to work, why for Phase 3 not randomise patients 1:1:2 to 100 mcg, 50 mcg, and placebo respectively? Data in vaccinated patients could then either be merged to calculate a single efficacy metric (as it was de facto done in the AstraZeneca vaccine trial) or synthesised through dose-response modeling (using immunological data). Such a trial may still be underpowered for proving non-inferiority of the lower dosage, but it provides many times more data than the original trial.

Clinical trials of efficacy against infection, not just against disease

Let us imagine a hypothetical epidemic, where cases are growing exponentially and the spread is not controlled, but a new vaccine potentially offers some protection against infection. The optimal dosing in the case of transmission-breaking vaccine is going to be different.[^4] Thus generating data on sterilising immunity may be very important for vaccine optimisation. This may look like "traditional" field trials with regular testing of a large population and studying secondary infections.

**What to do**

In both of these cases the objective would be two-fold

(1) consider trial design under realistic conditions (e.g. based on retrospective analysis of COVID)

(2) describe both risk-benefits of statistical trial designs that are not commonly used, in the sense of utility of generated information for both general licensure and making more optimal vaccine schedule choices (e.g. a trial with multiple doses may get closer to socially optimal dose but reduce overall approval probability), but also accounting for patient risks and costs

(3) (optionally) in both cases consider how these data could be generated by using human challenge trials

[^1]: Why investigate this more? Even if researchers switch their mindset to more comprehensively testing more doses and schedules early in vaccine development, there is no guarantee that this will yield optimal results. On the other hand, it's unclear whether some of the modelling approaches are practically valuable or just mainly proofs-of-concept that are not ready to be used in most practical cases.

[^2]: A good example for work in that category is a recent article showing safety and growing adoption of human challenge studies.

[^3]: Why is this not done? Developers don't see this as an option, because trials are so expensive and they would like to avoid anything that would increase trial sizes, even modestly. Most researchers and regulators may be averse to considering this because they are generally resistant to synthesising information in clinical trials: we demonstrated this unwillingness to generalise in several examples throughout the document.

[^4]: If we knew the vaccine offered protection from infection, then it may be optimal to quickly give it to as many people as possible (at the dose at which there is enough efficacy against infection), to break transmission/reach herd immunity. If that is not the case, then we may focus on vaccinating the at-risk individuals (at the dose at which there is efficacy against disease).
